spring:
  application:
    name: wishBlind
  profiles:
    active: dev   # 기본적으로 dev 프로파일 활성화

server:
  port: ${SERVER_PORT:8080}

app:
  invite-base-url: ${INVITE_BASE_URL:http://localhost:8080/invite}

logging:
  level:
    root: info
